#!/bin/sh

set -e

cd "$(dirname $0)"

find src -name \*.[ch] -print0 \
    | xargs -0 splint -Iinclude -Isplint-include -I build \
        -DCPORTAGE_COMPILATION -DGETTEXT_PACKAGE=\"cportage\" \
        -Dyyscan_t=gpointer \
        -warnposix -strict -nullstate -exportlocal -protoparamname -sizeoftype \
        -sysdirs src/cmerge:splint-include:/usr -sysdirerrors -warnmissingglobs \
        -boundsread -boundswrite -exportiter -fcnuse -enummemuse -typeuse -compmempass 2>&1
